#!/usr/bin/env python
import shiftpi
import RPi.GPIO as GPIO
#shiftpi.pinsSetup(**{"ser": 26, "rclk": 19, "srclk": 13})
shiftpi.shiftRegisters(2)

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM) # use Broadcom GPIO numbers

# Setup Output Enable pin
OE = 27 # Pin 13 output enable
GPIO.setup(OE, GPIO.OUT)
GPIO.output(OE, 0) #set output enable LOW to enable shift registers

# set all shift register pins HIGH
shiftpi.startupMode(shiftpi.HIGH, True)

# set all shift register pins LOW, one at a time
shiftpi.delay(500)
i = 0
while i < 17:
  shiftpi.digitalWrite(i, shiftpi.LOW)
  i = i+1
  shiftpi.delay(500)

# turns all shift register pins to HIGH
shiftpi.digitalWrite(shiftpi.ALL, shiftpi.HIGH)

GPIO.cleanup()
print("Good by")
exit
